pipeline:
  name: bguhj
  identifier: 'bb'
  projectIdentifier: default_project
  orgIdentifier: defaul
  tags: {}
  stages:
    - stage:
        name: vfads
        identifier: vfads
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10s
        tags: {}
