pipeline:
  name: kushal
  identifier: IDP dsadas     9831209382103981&#&$&&$&$    _Provision_New_User_Account_N
  projectIdentifier: demo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: e
        identifier: e
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10s
              - step:
                  type: Wait
                  name: Wait_2
                  identifier: Wait_2
                  spec:
                    duration: 10s
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
