pipeline:
  name: ci-cd
  identifier: IDP dsadas     9831292103981#&$&&$&    _Proviseon_New_User_Account_Ne
  projectIdentifier: demo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dfa
        identifier: dfa
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "kushal"
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
