pipeline:
  name: hgf
  identifier: IDP dsadas     9831209382103981&#&$&&$&$    _Provision_New_User_Account_New
  projectIdentifier: demo2
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: hyrtgfb
        identifier: hyrtgfb
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10s
        tags: {}
