pipeline:
  name: test-m2
  identifier: testm2
  projectIdentifier: demo1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sgtage1
        identifier: sgtage1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        sendGitStatus:
          enabled: true
          name: test
